# Generated by Django 6.0.3 on 2026-04-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asdf', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
